// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Header': string;
  'MenuContainer': string;
  'NavigationContainer': string;
  'header': string;
  'menuContainer': string;
  'navigationContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
